### PR TITLE
Add support for Sinatra 2

### PR DESCRIPTION
**Pull request by jkowens**
Everything seems to work just fine with Sinatra 2, I just updated the gemspec and tweaked the spec helper.

### CODE REVIEW

**Comment by jaredbeck** [comment]
Thanks Jordan, I'll cut a release.

**Comment by jkowens** [comment]
Great thanks!

**Comment by jaredbeck** [comment]
Released in `0.2.0`.

Would you be interested in helping to maintain this repo, Jordan?

**Comment by jkowens** [comment]
@jaredbeck I would be willing to help out as much as possible. As I'm sure you'll agree, there's never enough time in a day 😅

**Comment by jaredbeck** [comment]
Thanks Jordan, I sent you a collaborator invitation. :heart:

**Pull request merged**
